language: julia
os:
  - linux
  - osx
  - windows
    # - arm64
julia:
  - 1.3
notifications:
  email: false
script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/KristofferC/Clang_jll.jl")); Pkg.test()'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
