name = "PackageCompilerX"
uuid = "dffaa6cc-da53-48e5-b007-4292dfcc27f1"
authors = ["KristofferC <kcarlsson89@gmail.com>"]
version = "0.1.0"

[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
